# Generated by Django 4.2.23 on 2025-07-29 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('key_features', models.JSONField(blank=True, null=True)),
                ('categories', models.CharField(choices=[('shoes', 'Basketball Shoes'), ('apparel', 'Apparel'), ('equipment', 'Equipment'), ('accessories', 'Accessories')], max_length=20)),
                ('sizes', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('owned_duration', models.CharField(blank=True, choices=[('less-than-week', 'Less than a week'), ('1-2-weeks', '1-2 weeks'), ('1-month', 'About a month'), ('2-6-months', '2-6 months'), ('6-months-plus', '6+ months'), ('1-year-plus', 'Over a year')], max_length=20, null=True)),
                ('recommend', models.CharField(blank=True, choices=[('definitely', 'Definitely'), ('probably', 'Probably'), ('maybe', 'Maybe'), ('probably-not', 'Probably not'), ('definitely-not', 'Definitely not')], max_length=20, null=True)),
                ('pros', models.TextField(blank=True, null=True)),
                ('cons', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.profile')),
            ],
        ),
    ]
